[2024-07-18 06:36:12,963] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: xcom_example_dag.pull_task 2024-04-17T00:00:00+00:00 [queued]>
[2024-07-18 06:36:13,043] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: xcom_example_dag.pull_task 2024-04-17T00:00:00+00:00 [queued]>
[2024-07-18 06:36:13,044] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-07-18 06:36:13,045] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2024-07-18 06:36:13,045] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-07-18 06:36:13,093] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): pull_task> on 2024-04-17T00:00:00+00:00
[2024-07-18 06:36:13,099] {standard_task_runner.py:52} INFO - Started process 210 to run task
[2024-07-18 06:36:13,107] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'xcom_example_dag', 'pull_task', '2024-04-17T00:00:00+00:00', '--job-id', '582', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/xcom.py', '--cfg-path', '/tmp/tmpbs_ffo6e', '--error-file', '/tmp/tmp1t_gnody']
[2024-07-18 06:36:13,130] {standard_task_runner.py:77} INFO - Job 582: Subtask pull_task
[2024-07-18 06:36:13,559] {logging_mixin.py:104} INFO - Running <TaskInstance: xcom_example_dag.pull_task 2024-04-17T00:00:00+00:00 [running]> on host a868c7bacc12
[2024-07-18 06:36:13,867] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=xcom_example_dag
AIRFLOW_CTX_TASK_ID=pull_task
AIRFLOW_CTX_EXECUTION_DATE=2024-04-17T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-04-17T00:00:00+00:00
[2024-07-18 06:36:13,890] {logging_mixin.py:104} INFO - Pulled message: Hello from push_function!
[2024-07-18 06:36:13,895] {python.py:118} INFO - Done. Returned value was: None
[2024-07-18 06:36:13,943] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=xcom_example_dag, task_id=pull_task, execution_date=20240417T000000, start_date=20240718T063612, end_date=20240718T063613
[2024-07-18 06:36:14,130] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-18 06:36:14,175] {local_task_job.py:146} INFO - Task exited with return code 0
