[2024-07-18 06:35:37,632] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: xcom_example_dag.push_task 2024-04-14T00:00:00+00:00 [queued]>
[2024-07-18 06:35:37,847] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: xcom_example_dag.push_task 2024-04-14T00:00:00+00:00 [queued]>
[2024-07-18 06:35:37,889] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-07-18 06:35:37,890] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2024-07-18 06:35:37,891] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-07-18 06:35:38,050] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): push_task> on 2024-04-14T00:00:00+00:00
[2024-07-18 06:35:38,070] {standard_task_runner.py:52} INFO - Started process 3115 to run task
[2024-07-18 06:35:38,125] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'xcom_example_dag', 'push_task', '2024-04-14T00:00:00+00:00', '--job-id', '561', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/xcom.py', '--cfg-path', '/tmp/tmponvherbj', '--error-file', '/tmp/tmpkiq5zld7']
[2024-07-18 06:35:38,143] {standard_task_runner.py:77} INFO - Job 561: Subtask push_task
[2024-07-18 06:35:38,552] {logging_mixin.py:104} INFO - Running <TaskInstance: xcom_example_dag.push_task 2024-04-14T00:00:00+00:00 [running]> on host a868c7bacc12
[2024-07-18 06:35:38,948] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=xcom_example_dag
AIRFLOW_CTX_TASK_ID=push_task
AIRFLOW_CTX_EXECUTION_DATE=2024-04-14T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-04-14T00:00:00+00:00
[2024-07-18 06:35:39,094] {python.py:118} INFO - Done. Returned value was: None
[2024-07-18 06:35:39,251] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=xcom_example_dag, task_id=push_task, execution_date=20240414T000000, start_date=20240718T063537, end_date=20240718T063539
[2024-07-18 06:35:39,569] {local_task_job.py:77} ERROR - Received SIGTERM. Terminating subprocesses
[2024-07-18 06:35:39,759] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 3115
[2024-07-18 06:35:41,348] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-07-18 06:35:41,394] {process_utils.py:66} INFO - Process psutil.Process(pid=3115, status='terminated', exitcode=1, started='06:35:37') (3115) terminated with exit code 1
