[2024-07-18 06:01:42,066] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v3.third_task 2024-07-18T06:01:40.101416+00:00 [queued]>
[2024-07-18 06:01:42,077] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v3.third_task 2024-07-18T06:01:40.101416+00:00 [queued]>
[2024-07-18 06:01:42,077] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-07-18 06:01:42,078] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2024-07-18 06:01:42,078] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-07-18 06:01:42,091] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): third_task> on 2024-07-18T06:01:40.101416+00:00
[2024-07-18 06:01:42,095] {standard_task_runner.py:52} INFO - Started process 931 to run task
[2024-07-18 06:01:42,098] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_first_dag_v3', 'third_task', '2024-07-18T06:01:40.101416+00:00', '--job-id', '20', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpafjv_mnn', '--error-file', '/tmp/tmp74b_ja0z']
[2024-07-18 06:01:42,101] {standard_task_runner.py:77} INFO - Job 20: Subtask third_task
[2024-07-18 06:01:42,140] {logging_mixin.py:104} INFO - Running <TaskInstance: our_first_dag_v3.third_task 2024-07-18T06:01:40.101416+00:00 [running]> on host a868c7bacc12
[2024-07-18 06:01:42,180] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v3
AIRFLOW_CTX_TASK_ID=third_task
AIRFLOW_CTX_EXECUTION_DATE=2024-07-18T06:01:40.101416+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-18T06:01:40.101416+00:00
[2024-07-18 06:01:42,181] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2024-07-18 06:01:42,182] {bash.py:158} INFO - Running command: echo hello world, this is the third task, it will run after first task and at the same time task 2
[2024-07-18 06:01:42,190] {bash.py:169} INFO - Output:
[2024-07-18 06:01:42,190] {bash.py:173} INFO - hello world, this is the third task, it will run after first task and at the same time task 2
[2024-07-18 06:01:42,191] {bash.py:177} INFO - Command exited with return code 0
[2024-07-18 06:01:42,215] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v3, task_id=third_task, execution_date=20240718T060140, start_date=20240718T060142, end_date=20240718T060142
[2024-07-18 06:01:42,239] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-18 06:01:42,270] {local_task_job.py:146} INFO - Task exited with return code 0
